### ISSUE TITLE
projection extension scope in Collection?

### ISSUE THREAD

**Issue by emmanuelmathot** [stac-extensions/projection#3]
### Context

- The scope of the extensions defines where the extensions fields can be found. 
- Implicitly, all item fields could be summarized in collection (Assumption)

### Questions

Does the scope define a strict limitation of where the field can be found? 
- If yes, then the `projection` extension is limited to `Item` and thus `proj:espg` should not be summarized as in the example in https://github.com/radiantearth/stac-spec/blob/master/examples/collection-only/collection.json
- If no, is it necessary to set the scope to collection in the extension definition?

Clarification is needed for the implementation of the helpers methods in the libraries implementing STAC spec and extensions.

**Comment by m-mohr** [comment]
It's "no". This is an oversight on our side, we should've added the scope Collection here. I added it now, which is just a bug fix as the schemas already support validating in collection assets and item asset definitions.

Validating the summaries is a weak point though. Due to the different structures the summaries have (array and stats object), the fields can't be validated (yet?). So the stac_extensions flag doesn't really apply for summaries and extensions, but only really applies to assets / item_assets in Collections.

**Comment by m-mohr** [comment]
See also https://github.com/radiantearth/stac-spec/issues/1077 for some more context and a change I'd like to propose.

**Comment by emmanuelmathot** [comment]
yes indeed, I am reviewing https://github.com/radiantearth/stac-spec/pull/1078 that helps me to understand how it is applied.
